package main

import (
	"bytes"
	"cmp"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// usize returns the number of bits of the smallest unsigned integer
// type that will hold n. Used to create the smallest possible slice of
// integers to use as indexes into the concatenated strings.
func usize(n int) int {
	switch {
	case n < 1<<8:
		return 8
	case n < 1<<16:
		return 16
	default:
		// 2^32 is enough constants for anyone.
		return 32
	}
}

// splitIntoRuns breaks the values into runs of contiguous sequences.
// For example, given 1,2,3,5,6,7 it returns {1,2,3},{5,6,7}.
// The input slice is known to be non-empty.
func splitIntoRuns(values []Value) [][]Value {
	// We use stable sort so the lexically first name is chosen for equal elements.
	slices.SortStableFunc(values, func(left, right Value) int {
		if left.signed {
			return cmp.Compare(int64(left.value), int64(right.value))
		}
		return cmp.Compare(left.value, right.value)
	})

	// Remove duplicates. Stable sort has put the one we want to print first,
	// so use that one. The String method won't care about which named constant
	// was the argument, so the first name for the given value is the only one to keep.
	// We need to do this because identical values would cause the switch or map
	// to fail to compile.
	j := 1
	for i := 1; i < len(values); i++ {
		if values[i].value != values[i-1].value {
			values[j] = values[i]
			j++
		}
	}
	values = values[:j]
	runs := make([][]Value, 0, 10)
	for len(values) > 0 {
		// One contiguous sequence per outer loop.
		i := 1
		for i < len(values) && values[i].value == values[i-1].value+1 {
			i++
		}
		runs = append(runs, values[:i])
		values = values[i:]
	}
	return runs
}

func fnv1a32(s string) uint32 {
	var h uint32 = 2166136261
	for i := 0; i < len(s); i++ {
		h ^= uint32(s[i])
		h *= 16777619
	}
	return h
}

// Generator holds the state of the analysis. Primarily used to buffer
// the output for format.Source.
type Generator struct {
	buf bytes.Buffer // Accumulated output.

	lookup string
	json   bool
}

func (g *Generator) Printf(format string, args ...any) {
	fmt.Fprintf(&g.buf, format, args...)
}

func (g *Generator) genPackage(pkg *Package, types []string, dir, output string) []string {
	g.prologue(pkg.name)

	// Run generate for types that can be found. Keep the rest for the remainingTypes iteration.
	var foundTypes, remainingTypes []string

	typeValues := pkg.findValues(types...)
	for typeName, values := range typeValues {
		if len(values) > 0 {
			g.genType(typeName, values)
			foundTypes = append(foundTypes, typeName)
		} else {
			remainingTypes = append(remainingTypes, typeName)
		}
	}

	if len(foundTypes) == 0 {
		// This package didn't have any of the relevant types, skip writing a file.
		return types
	}
	if len(remainingTypes) > 0 && output != "" {
		log.Fatalf("cannot write to single file (-output=%q) when matching types are found in multiple packages", output)
	}
	types = remainingTypes

	// Format the output.
	src := g.format()

	// Write to file.
	if output == "" {
		// Type names will be unique across packages since only the first
		// match is picked.
		// So there won't be collisions between a package compiled for tests
		// and the separate package of tests (package foo_test).
		output = filepath.Join(dir, baseName(pkg, foundTypes[0]))
	}
	err := os.WriteFile(output, src, 0o644)
	if err != nil {
		log.Fatalf("writing output: %s", err)
	}
	return types
}

func (g *Generator) prologue(pkgname string) {
	// Print the header and package clause.
	g.Printf("// Code generated by \"%s\"; DO NOT EDIT.\n", strings.Join(os.Args, " "))
	g.Printf("\n")
	g.Printf("package %s", pkgname)
	g.Printf("\n")
	g.Printf("import (\n")
	if g.json {
		g.Printf("\"encoding/json\"\n") // Used by all methods.
		g.Printf("\"reflect\"\n")       // Used by all methods.
	}
	g.Printf("\"strconv\"\n") // Used by all methods.
	g.Printf(")\n")
}

// format returns the gofmt-ed contents of the Generator's buffer.
func (g *Generator) format() []byte {
	src, err := format.Source(g.buf.Bytes())
	if err != nil {
		// Should never happen, but can arise when developing this code.
		// The user can compile the output to see the error.
		log.Printf("warning: internal error: invalid Go generated: %s", err)
		log.Printf("warning: compile the package to analyze the error")
		return g.buf.Bytes()
	}
	return src
}

// declareIndexAndNameVars declares the index slices and concatenated names
// strings representing the runs of values.
func (g *Generator) declareIndexAndNameVars(runs [][]Value, typeName string) {
	var indexes, names []string
	for i, run := range runs {
		index, name := g.createIndexAndNameDecl(run, typeName, fmt.Sprintf("_%d", i))
		if len(run) != 1 {
			indexes = append(indexes, index)
		}
		names = append(names, name)
	}
	g.Printf("const (\n")
	for _, name := range names {
		g.Printf("%s\n", name)
	}
	g.Printf(")\n\n")

	if len(indexes) > 0 {
		g.Printf("var (")
		for _, index := range indexes {
			g.Printf("%s\n", index)
		}
		g.Printf(")\n\n")
	}
}

// declareIndexAndNameVar is the single-run version of declareIndexAndNameVars
func (g *Generator) declareIndexAndNameVar(run []Value, typeName string) {
	index, name := g.createIndexAndNameDecl(run, typeName, "")
	g.Printf("const %s\n", name)
	g.Printf("var %s\n", index)
}

// createIndexAndNameDecl returns the pair of declarations for the run. The caller will add "const" and "var".
func (g *Generator) createIndexAndNameDecl(run []Value, typeName string, suffix string) (string, string) {
	var b bytes.Buffer
	indexes := make([]int, len(run))
	for i := range run {
		b.WriteString(run[i].repr)
		indexes[i] = b.Len()
	}
	nameConst := fmt.Sprintf("_%s_name%s = %q", typeName, suffix, b.String())
	nameLen := b.Len()
	b.Reset()
	fmt.Fprintf(&b, "_%s_index%s = [...]uint%d{0, ", typeName, suffix, usize(nameLen))
	for i, v := range indexes {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%d", v)
	}
	b.WriteString("}")
	return b.String(), nameConst
}

// declareNameVars declares the concatenated names string representing all the values in the runs.
func (g *Generator) declareNameVars(runs [][]Value, typeName string, suffix string) {
	g.Printf("const _%s_name%s = \"", typeName, suffix)
	for _, run := range runs {
		for i := range run {
			g.Printf("%s", run[i].repr)
		}
	}
	g.Printf("\"\n")
}

// genType produces the String method for the named type.
func (g *Generator) genType(typeName string, values []Value) {
	if g.json && g.lookup == "" {
		g.lookup = "_lookup_{}"
	}

	g.buildCheck(values)
	if g.lookup != "" {
		// For each value, you'll get 4 lines of source-code. This
		// might overfloat the resulting file and we're choosing to
		// generate a less verbose technique.
		switch n := len(values); {
		case n <= 500:
			g.buildLookup(typeName, values) // fnv32 hash-switch
		case n <= 5000:
			g.buildLookupBinary(typeName, values) // binary search
		default:
			g.buildLookupMap(typeName, values) // map
		}
	}
	runs := splitIntoRuns(values)

	// The decision of which pattern to use depends on the number of
	// runs in the numbers. If there's only one, it's easy. For more than
	// one, there's a tradeoff between complexity and size of the data
	// and code vs. the simplicity of a map. A map takes more space,
	// but so does the code. The decision here (crossover at 10) is
	// arbitrary, but considers that for large numbers of runs the cost
	// of the linear scan in the switch might become important, and
	// rather than use yet another algorithm such as binary search,
	// we punt and use a map. In any case, the likelihood of a map
	// being necessary for any realistic example other than bitmasks
	// is very low. And bitmasks probably deserve their own analysis,
	// to be done some other day.
	switch {
	case len(runs) == 1:
		g.buildOneRun(runs, typeName)
	case len(runs) <= 10:
		g.buildMultipleRuns(runs, typeName)
	default:
		g.buildMap(runs, typeName)
	}
	if g.json {
		g.buildJson(typeName)
	}
}

func (g *Generator) buildCheck(values []Value) {
	// Generate code that will fail if the constants change value.
	g.Printf("func _() {\n")
	g.Printf("// An \"invalid array index\" compiler error signifies that the constant values have changed.\n")
	g.Printf("// Re-run the stringer command to generate them again.\n")
	g.Printf("var x [1]struct{}\n")
	for _, v := range values {
		g.Printf("_ = x[%s - %s]\n", v.original, v.str)
	}
	g.Printf("}\n")
}

// buildOneRun generates the variables and String method for a single run of contiguous values.
func (g *Generator) buildOneRun(runs [][]Value, typeName string) {
	values := runs[0]
	g.Printf("\n")
	g.declareIndexAndNameVar(values, typeName)
	g.Printf(stringOneRun, typeName, values[0].String())
}

// Arguments to format are:
//
//	[1]: type name
//	[2]: lowest defined value for type, as a string
const stringOneRun = `func (i %[1]s) String() string {
	idx := int(i) - %[2]s
	if i < %[2]s || idx >= len(_%[1]s_index)-1 {
		return "%[1]s(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _%[1]s_name[_%[1]s_index[idx] : _%[1]s_index[idx+1]]
}
`

// buildMultipleRuns generates the variables and String method for multiple runs of contiguous values.
// For this pattern, a single Printf format won't do.
func (g *Generator) buildMultipleRuns(runs [][]Value, typeName string) {
	g.Printf("\n")
	g.declareIndexAndNameVars(runs, typeName)
	g.Printf("func (i %s) String() string {\n", typeName)
	g.Printf("switch {\n")
	for i, values := range runs {
		if len(values) == 1 {
			g.Printf("case i == %s:\n", &values[0])
			g.Printf("return _%s_name_%d\n", typeName, i)
			continue
		}
		if values[0].value == 0 && !values[0].signed {
			// For an unsigned lower bound of 0, "0 <= i" would be redundant.
			g.Printf("case i <= %s:\n", &values[len(values)-1])
		} else {
			g.Printf("case %s <= i && i <= %s:\n", &values[0], &values[len(values)-1])
		}
		if values[0].value != 0 {
			g.Printf("i -= %s\n", &values[0])
		}
		g.Printf("return _%s_name_%d[_%s_index_%d[i]:_%s_index_%d[i+1]]\n",
			typeName, i, typeName, i, typeName, i)
	}
	g.Printf("default:\n")
	g.Printf("return \"%s(\" + strconv.FormatInt(int64(i), 10) + \")\"\n", typeName)
	g.Printf("}\n")
	g.Printf("}\n")
}

// Argument to format is the type name.
const stringMap = `func (i %[1]s) String() string {
	if str, ok := _%[1]s_map[i]; ok {
		return str
	}
	return "%[1]s(" + strconv.FormatInt(int64(i), 10) + ")"
}
`

// buildMap handles the case where the space is so sparse a map is a reasonable fallback.
// It's a rare situation but has simple code.
func (g *Generator) buildMap(runs [][]Value, typeName string) {
	g.Printf("\n")
	g.declareNameVars(runs, typeName, "")
	g.Printf("\nvar _%s_map = map[%s]string{\n", typeName, typeName)
	n := 0
	for _, values := range runs {
		for _, value := range values {
			g.Printf("%s: _%s_name[%d:%d],\n", &value, typeName, n, n+len(value.repr))
			n += len(value.repr)
		}
	}
	g.Printf("}\n\n")
	g.Printf(stringMap, typeName)
}

func (g *Generator) buildLookup(typeName string, values []Value) {
	g.Printf("\n")

	funcName := strings.Replace(g.lookup, "{}", typeName, 1)
	g.Printf("func %s(name string) (%s, bool) {\n", funcName, typeName)
	g.Printf("//fnv1a32 hash\n")
	g.Printf("var h uint32 = 2166136261\n")
	g.Printf("for i := 0; i < len(name); i++ {\n")
	g.Printf("h ^= uint32(name[i])\n")
	g.Printf("h *= 16777619\n")
	g.Printf("}\n")
	g.Printf("\n")
	g.Printf("switch h {\n")

	// group by hash
	type entry struct {
		hash uint32
		name string
		val  string
	}
	ents := make([]entry, len(values))
	for i, v := range values {
		ents[i] = entry{
			hash: fnv1a32(v.repr),
			name: v.repr,
			val:  v.original,
		}
	}

	slices.SortFunc(ents, func(left, right entry) int {
		if left.hash != right.hash {
			return cmp.Compare(left.hash, right.hash)
		}
		return strings.Compare(left.name, right.name)
	})

	// emit switch cases, handling collisions
	prev := uint32(0xffffffff)
	for _, ent := range ents {
		h := ent.hash
		if h != prev {
			g.Printf("case 0x%08x:\n", h)
			prev = h
		}
		g.Printf("if name == %q {\n", ent.name)
		g.Printf("return %s, true\n", ent.val)
		g.Printf("}\n")
	}

	g.Printf("}\n")
	g.Printf("return 0, false\n")
	g.Printf("}\n")
}

func (g *Generator) buildLookupBinary(typeName string, values []Value) {
	g.Printf("\n")

	// copy values
	slices.SortFunc(values, func(left, right Value) int {
		if left.repr != right.repr {
			return strings.Compare(left.repr, right.repr)
		}
		return strings.Compare(left.original, right.original)
	})

	//   const _<T>_name_lookup = "..."
	//   var   _<T>_index_lookup = [...]uintN{...}
	indexDecl, nameDecl := g.createIndexAndNameDecl(values, typeName, "_lookup")
	g.Printf("const %s\n", nameDecl)
	g.Printf("var %s\n", indexDecl)

	g.Printf("var _%s_value_lookup = [...]%s{\n", typeName, typeName)
	for _, v := range values {
		g.Printf("%s,\n", v.original)
	}
	g.Printf("}\n\n")

	funcName := strings.Replace(g.lookup, "{}", typeName, 1)
	g.Printf("func %s(name string) (%s, bool) {\n", funcName, typeName)

	g.Printf("lo, hi := 0, len(_%s_value_lookup)\n", typeName)
	g.Printf("for lo < hi {\n")
	g.Printf("mid := int(uint(lo+hi) >> 1)\n")
	g.Printf("s := _%s_name_lookup[_%s_index_lookup[mid]:_%s_index_lookup[mid+1]]\n",
		typeName, typeName, typeName)

	g.Printf("if name == s {\n")
	g.Printf("return _%s_value_lookup[mid], true\n", typeName)
	g.Printf("}\n")
	g.Printf("if name < s {\n")
	g.Printf("hi = mid\n")
	g.Printf("} else {\n")
	g.Printf("lo = mid + 1\n")
	g.Printf("}\n")
	g.Printf("}\n")
	g.Printf("return 0, false\n")
	g.Printf("}\n")
}

func (g *Generator) buildLookupMap(typeName string, values []Value) {
	g.Printf("\n")

	g.Printf("var _%s_lookup = map[string]%s{\n", typeName, typeName)
	for _, v := range values {
		g.Printf("%q: %s,\n", v.repr, v.original)
	}
	g.Printf("}\n")

	funcName := strings.Replace(g.lookup, "{}", typeName, 1)
	g.Printf("func %s(name string) (%s, bool) {\n", funcName, typeName)
	g.Printf("value, ok := _%s_lookup[name]\n", typeName)
	g.Printf("return value, ok\n")
	g.Printf("}\n")
}

func (g *Generator) buildJson(typeName string) {
	lookupFunc := strings.Replace(g.lookup, "{}", typeName, 1)
	g.Printf("func (i %s) MarshalJSON() ([]byte, error) {\n", typeName)
	g.Printf("return json.Marshal(i.String())\n")
	g.Printf("}\n")
	g.Printf("\n")
	g.Printf("func (i *%s) UnmarshalJSON(b []byte) error {\n", typeName)
	g.Printf("var value any\n")
	g.Printf("if err := json.Unmarshal(b, &value); err != nil {\n")
	g.Printf("return err\n")
	g.Printf("}\n")
	g.Printf("switch v := value.(type) {\n")
	g.Printf("case string:\n")
	g.Printf("m, ok := %s(v)\n", lookupFunc)
	g.Printf("if !ok {\n")
	g.Printf("return &json.UnmarshalTypeError{Value: string(b), Type: reflect.TypeOf(%s(0))}\n", typeName)
	g.Printf("}\n")
	g.Printf("*i = m\n")
	g.Printf("case float64:\n")
	g.Printf("*i = %s(v)\n", typeName)
	g.Printf("default:\n")
	g.Printf("return &json.UnmarshalTypeError{Value: string(b), Type: reflect.TypeOf(%s(0))}\n", typeName)
	g.Printf("}\n")
	g.Printf("return nil\n")
	g.Printf("}\n")
}
